- name: Profile Readme Stats
  uses: teoxoy/profile-readme-stats@v1.2

on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: appleboy
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Taipei
